# Generated by Django 2.0.2 on 2018-04-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180411_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='major_upp',
            new_name='major_sweden',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='unv_upp',
            new_name='unv_sweden',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='core.UserProfile'),
        ),
    ]
